apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-insider-league
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony-insider-league
  template:
    metadata:
      labels:
        app: symfony-insider-league
    spec:
      containers:
        - name: symfony-app
          image: vikt0r7/symfony-insider-league:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: "prod"
