apiVersion: v1
kind: Service
metadata:
  name: symfony-service
spec:
  type: NodePort
  selector:asdsa
    app: symfony-insider-league
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
