name: Build & Deploy

on:
    push:
        branches: [ main ]

jobs:
    build-frontend:
        name: Build Vite Frontend
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Node
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install dependencies
                run: npm ci

            -   name: Build frontend
                run: npm run build

            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: frontend-build
                    path: public/build

    deploy:
        name: Deploy Symfony App
        runs-on: ubuntu-latest
        needs: build-frontend

        steps:
            -   uses: actions/checkout@v4

            -   name: Download frontend build
                uses: actions/download-artifact@v4
                with:
                    name: frontend-build
                    path: public/build

            -   name: Deploy to Server (test)
                run: echo "ls"
